cat("StatsPaper Project Package Load:") 

require(tidyverse)
require(lme4)
require(data.table)
require(moments)
require(lmerTest)
require(lattice)
require(psych)
require(effects)
require(interactions)
